name: flutter_dio_bloc_pagination
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
      sdk: flutter
  cupertino_icons:
  dio:
  bloc: ^8.1.2
  flutter_bloc: ^8.1.0
  equatable:
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  rxdart:
  welltested_annotation: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  mockito:
  json_serializable: ^6.7.1



flutter:
  uses-material-design: true

# assets:
#  - images/a_dot_burr.jpeg
#  - images/a_dot_ham.jpeg



# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
